### ISSUE TITLE
Request textDocument/definition failed.

### ISSUE THREAD

**Issue by samuela** [DafnyVSCode/Dafny-VSCode#45] opened 2019-03-12 00:08 UTC
This shows up in the output of the Dafny Language Server:
```
[Error - 4:11:21 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'then' of null
  Code: -32603 
```

**Comment by fabianhauser** [comment] 2019-03-18 14:22
Duplicate of #12

**Closed by fabianhauser** 2019-03-18 14:22 UTC
Labels: bug, duplicate
