### ISSUE TITLE
Autocomplete doesn't work on new install

### ISSUE THREAD

**Issue by seanmcl** [DafnyVSCode/Dafny-VSCode#33] opened 2018-07-19 06:03 UTC
I installed Dafny and VSCode from scratch.  While Dafny itself seems to be functioning fine, the auto-complete fails with the following message.   

```
[Error - 6:59:36 AM] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'getText' of undefined
  Code: -32603 
```

The error repeats whenever I type '.'  How can I start debugging this?
<img width="971" alt="screen shot 2018-07-19 at 7 03 01 am" src="https://user-images.githubusercontent.com/110393/42924389-d4f66470-8b21-11e8-8277-98d4d92a127b.png">

**Comment by fmehta** [comment] 2018-07-20 09:37
Hi Sean,
Thanks for posting this issue. From the looks of it, it seems to be a duplicate of #12. I am therefore closing this thread. In case you have any other relevant information, please use #12.

Farhad

**Comment by fmehta** [comment] 2018-07-20 09:37
Duplicate of #12.

**Closed by fmehta** 2018-07-20 09:37 UTC
